version: '3.7'

services: 
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: 'eventals'
      ports:
        - 8080:80
      volumes:
        - ./:/var/www/html

    db:
      image: mysql:5.7
      restart: always
      ports: 
        - "13308:3306"
      environment:
        MYSQL_DATABASE: 'eventsdb'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_ROOT_PASSWORD: "2"
        MYSQL_USER: root
        MYSQL_PASSWORD: 
      volumes:
        - ./db:/var/lib/mysql

    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       restart: always
       ports:
         - "8081:80"
       environment:
         PMA_HOST: db
         MYSQL_ROOT_PASSWORD: "2"
